swaptions: use pthreads instead of tbblib
Otherwise fails with:

```
HJM_SimPath_Forward_Blocking.cpp:10:37: fatal error: tbb/task_scheduler_init.h: No such file or directory
 #include "tbb/task_scheduler_init.h"
```